### ISSUE TITLE
Snake Disconnects after Death

### ISSUE THREAD

**Issue by MasonBurdette** [MasonBurdette/slither-client#2]
As stated in title, I'm working on fixing it before release

**Comment by joery1337** [comment]
Do you already have all the packets, otherwise it would be a waste of time for me to do the same.

**Comment by Coder-256** [comment]
@joery1337 He said that [he is working on it](https://github.com/MasonBurdette/slither-client/issues/1#issuecomment-205985588).

**Comment by joery1337** [comment]
@Coder-256 that does not answer my question, it would be useful if he says what he already has figured out.

**Comment by Coder-256** [comment]
@joery1337 I misunderstood your original question, but I do completely agree that he should share what he has so far.

**Comment by ThunderGemios10** [comment]
@Coder-256 I agree, But by the looks of it, It looks like he got nothing as of the moment.

**Comment by MasonBurdette** [comment]
At the moment @ThunderGemios10 is partially right, I have very little.

**Comment by MasonBurdette** [comment]
Fixed it
