### ISSUE TITLE
Potentially useful information

### ISSUE THREAD

**Issue by Coder-256** [MasonBurdette/slither-client#3]
First of all, congratulations on your amazing work so far!

I found this and thought it could be helpful:

I just discovered that there are 17 different scripts just sitting in the `slither.io` server, numbered `game28.js` to `game44.js`, `game44.js` being the (presumably latest) current version used by the web client. They are accessed like:

    http://slither.io/s/game##.js

For example:

    http://slither.io/s/game44.js

In addition, **I found [a hidden testing mode](http://slither.io/?/testing)!!!** I have no idea what half of the information means. Maybe you could figure it out! I hope this helps.

All I ask in return for this information is that you release a beta, but it's totally up to you. I would love to work on it, which is why I'm asking.

**Comment by MasonBurdette** [comment]
Well I had everything except the testing mode.  How'd you find that?!
Also I'm planning to get the first update out soon..

**Comment by ItzLevvie** [comment]
I already knew that, ;P

**Comment by ThunderGemios10** [comment]
I was hoping that testing mode is the admin control panel xD

**Comment by Coder-256** [comment]
@ThunderGemios10 It's not. It just logs information. :disappointed:

**Comment by ThunderGemios10** [comment]
@Coder-256 darn... We actually i'm glad, Because if anyone finds this, Slither.io would be in chaos right now xD

**Comment by joery1337** [comment]
![](http://i.imgur.com/QgKw7E8.png)
It just means how many bytes are received per packet id.

I am going to figure out how those sectors work.

**Comment by Coder-256** [comment]
Does anybody know what the percentages are? Or what the square color means? Or why testing mode displays "ayy lmao" while the page is loading (possible alien activity?)?

**Comment by joery1337** [comment]
Percentage of received bytes per packet, those squares are sectors.

**Comment by Coder-256** [comment]
@joery1337
1. OK.
2. I meant, what are the different colors (green vs grey squares)?
3. [That was a joke](http://knowyourmeme.com/memes/ayy-lmao).

**Comment by ThunderGemios10** [comment]
@joery1337 That's alot of bytes...

**Comment by MasonBurdette** [comment]
Alright this isn't really an issue anymore, thanks for informing me.
