### ISSUE TITLE
Abandoned the project - The real reason

### ISSUE THREAD

**Issue by Zephyr1338** [MasonBurdette/slither-client#6]
This project was not infact abandoned because of "time" it was done because the creator of this project is not that good at programming, I've taken a look at the code left and the "initPacket" is being sent is formatted incorrectly. The packet was even fixed to be closer to the correct packet by someone else.

Anyway this is just so you know what actually happened if you want to see a client which is ACTUALLY in development with pictures, just check out my repository <a href="https://github.com/Zephyr1338/slither.io-bot" />here</a>

**Comment by Coder-256** [comment]
@Zephyr1338 Github is not for competition. Nor is it for insults. See the [Open Source Initiative website](https://opensource.org/about). Also, some people like @ThunderGemios10 do have lots of public (open source) progress. See the [Clither Project](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md).

**Comment by MasonBurdette** [comment]
@Zephyr1338  i honestly don't care

**Comment by Zephyr1338** [comment]
k
