### ISSUE TITLE
I'd be down to take over

### ISSUE THREAD

**Issue by pmartijena** [MasonBurdette/slither-client#7]
I have some free time on my hands, as I've taken a leave of absence from my job (which coincidentally was working w the mean stack) to focus on school. I've been working w node and javascript professionally for a while now, so I'm sure I could do a great job with it :-). Lmk

**Comment by ThunderGemios10** [comment]
You can just fork it and continue it there.

**Comment by MasonBurdette** [comment]
If u do I'll change readme with link to ur repo
